### ISSUE TITLE
[Question] How to install minera for networked miners only

### ISSUE THREAD

**Issue by gnanet** [getminera/minera#197]
I saw that minera is getting better and better in working witth networked miners too, and i know that inspecting the install scripts more deeply could be for me a way to find out, how to set up manually minera for "networked miners only".

But may i ask for help what parts of the installation script i can/should skip, to have a minera installation, that only monitors/manages networked miners?

**Comment by michelem09** [comment]
You can't skip anything because you still need to run the install script, but you could comment this line:

`su - minera -c "/var/www/minera/build_miner.sh all"`

https://github.com/getminera/minera/blob/master/install_minera.sh#L107

and it will skip the build for the local miner softwares you don't need with networked ones.
