### ISSUE TITLE
Minera 0.9 on pi3 : localhost/minera login with default user 'minera' and passwd not working

### ISSUE THREAD

**Issue by aleifuu** [getminera/minera#203]
Running minera 0.9 on raspberry pi3 

**Problem**
I followed the wiki on manually installing minera on pi3 
I only needed to instal redis-server by 
> sudo apt-get install -y redis-server

 I have webserver running Apache and everything else running

When going to localhost/minera, the login page loads up fine, but typing any password and login,
the page won't budge from the login page

**Could it be : ?**
1. My pi3 doesn't have php7.0 yet. last time I check no official repo is out for 7.0 yet so I'm 
    still using php5.0. Can Minera v0.9 support with php5.0 or not ?

2. In the login page, it shows Minera status as 'Offline'. How do you turn them 'Online' ? 
    or it supposed to be like that unless you succesfully login into it ?

I intend to use Minera to monitor tpruvot's cpuminer-multi as that's the one I'm using right now and I was told Minera can support this with a bit of api-binding 

Cheers,

**Comment by michelem09** [comment]
PHP5 isn't supported anymore. If you get access you will not able to use it. You need PHP7.0.

Why do you use a manual install on a raspberry? Use the latest image available and flash your SD Card with that.

It's offline because you need to access it to start the miner and go online.

And did you run the install script? Do you have the minera user in your system? Warning because the install script is done for fresh systems it doesn't check if there is another web server (apache) running and It could brake your current system.

Listen to me, make a backup of current system (if you need) and start from the image: https://getminera.com/download/latest
