### ISSUE TITLE
Running & Configuring 2 ASIC miner programs (same time)

### ISSUE THREAD

**Issue by cmrockwell** [getminera/minera#204]
Hi. Great project. Really well done.

I'm currently mining a set of two Gekko 2PAC's USB miners sha256 using a custom miner 
https://github.com/vthoang/cgminer Thanks for having this already preinstalled. 

Now, I'm looking to add a Moonlander 2 set of 4 to mine scrypt using another custom miner bfgminer
https://github.com/jstefanop/bfgminer/releases/tag/bfgminer-5.4.2-futurebit2-beta2

Would it possible to run both at the same time? Looking at the interface, it seems I need to pick one to manage with Minera, and to run the other via command line. But it would be really cool to somehow manage the settings for both sets of miners in Minera as well as having stats for all the USB miners from both sets listed.

**Comment by michelem09** [comment]
Unfortunately Minera can handle only one miner per time. As you noticed you can always start all your "extra" miners manually but without having the stats on Minera or the settings manager.
I'm closing this because it's not something I will work on ever due to the way Minera is build now and the low request for something like this.

**Comment by cmrockwell** [comment]
OK. Thanks for the response. I might take a crack at implementing myself if I can find a bit of time.
