### ISSUE TITLE
Chip Temp on AntMiner S9s

### ISSUE THREAD

**Issue by jpbrewer** [getminera/minera#208]
Right now I believe that you are reporting the PCB temp and not the ASIC chip temps for the S9. The chip temps are the critical failure issue for these units.  The S9s log reports 3 chip temps (one for each ASIC board), these are real time.  I would request that the dashboard report all three temperatures (since they can vary quite a bit if trash or such gets into the heatsink).

I like how the currently shown dashboard CPU temp has a background color.  Recommended background color for the ASIC temperature readings:

<85 Blue (cool)
85 - 100 Green (normal)
100 to 110 Yellow (monitor carefully, near ASIC cutoff threshold of 115)
>110  (Critically close to or above ASIC cutoff threshold of 115)

Leaving the PCB temp on there would be a nice touch as well.  Great software, thanks!

**Comment by davidromayPB** [comment]
Hi guys, I was wondering if someone has the schematic or pcb files of Antminer S9.

I appreciate your answer.

Regards,

**Comment by IcedQuick** [comment]
Hi there, yes this would be great to address - it is a nightmare checking the individual temps of the S9 one by one if you have a large farm (this is the main reason I installed Minera).

**Comment by Wolf-Gate** [comment]
Hey IcedQuick, how did you manage to install it? Can you be so kind and tell me your actions step by step?

**Comment by IcedQuick** [comment]
@Wolf-Gate 

My hope was that Minera it would make temperate monitoring easier but really now it shows about as much relevant information as my online pool information shows.

Currently it is complicated with a variety of technologies / services in play. There may be a better approach; in a nutshell a separate local connect across the antminer I ranges setup already, trawl the network status page of each miner and extract the temps from the page. It is then posted to the local network machine which collates it locally for storage / consumption. This is secondarily sent to a seperate internet connected machine on the same local network for reporting when off site (separate from the core local network processes since I am paranoid :)

Further to this, I want to explore exhaust monitoring as it is more reliable than the PCB board temp here and more scalable than the above method as it forms part of miner hardware setup. With similar data capturing capabilities as current, it is my next step after trying Minera - it would be more  easily scalable, but requires one ethernet thermometer per miner (or on some designs I played around with one usb thermometer per miner).

In most cases it is easier to run an ethernet cable in my experience and you can get them relatively cheaply on Amazon or Alibaba - well worth the investment or as a secondary monitoring / alert system in my opinion.

In addition to the S9's, I currently have some D3's coming out of testing and into a new NiceHash farm... and I am wondering if the same issue will persist here (D3 is also reports three temps for the chips in addition to the PCB, with chain #1 always hotter, naturally like in the S9's).

My bottleneck right now is temperature monitoring and I am actively aiming towards some kind of temperate related IP alert system, with potential auto cut-offs to power supply. Alot of KVA's we have to deal with here so I will happily share once we get there.

The S9's peak temperate on chain #1 is around 77 degrees Celsius middle rows to 73 degrees Celsius outer rows, around midday in my highly optimised cooling setup here in Africa - so temperature monitoring is very important as no air-con is used. Keep in mind that most rate 85 degrees Celsius okay for the S9's but they dont operate well when they are hot and I want to prevent them hitting their limit before they are disengaged (apparently 100 degrees Celsius!).

Would be interested to hear what you / others have achieved temperature wise on the chains, especially chain #1 both in AND out of non-winter / snow / northern hemisphere conditions.
