### ISSUE TITLE
Raspberry PI B +

### ISSUE THREAD

**Issue by ChrisCalzaretta** [getminera/minera#226]
Using win 32 disk image and the 9.0 minera image. The Pi will not boot. The pi just stays at the colored screen and do not move forward.
I have had this installed and running on a Pi B 2015 model version 1.2 for almost 7 months or so.

I have tried the image twice, not to say i am not doing something wrong but it is very easy to get it up and running

I am going to try the manual way to get this up and running on the Pi B+

**Comment by gnanet** [comment]
As a daily linux user and IT guy, i would first check that the image is correctly on the SD card:

If you have access to a Linux Desktop, you could try to put the SD-Card into a reader, and check if you can access the main system partition, and if there is a separate one for the boot partition, also that.

Also you could try to reimage the SD card from the Linux desktop too with 
```
dd bs=4M if=minera-latest.img of=/dev/your-sd-card
```

And I know it is maybe a too a basic question, but you remembered to uncompress the zip file before trying to flash it, right?

**Comment by ChrisCalzaretta** [comment]
yes. The card i can pull out of the B+ and put it in the 1.2 pi version and
it works

**Comment by michelem09** [comment]
What's the version in B+ you pull out?

**Comment by ChrisCalzaretta** [comment]
Not sure what you are asking It is the brand new version of the pi
https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/

it is just the latest raspberry pi.

I did get it to work when i did the manual setup. But i could not use the
Minera pre baked image.  The image i could not get to work was
"minera-0.9.0.img"

Thanks

Chris


On Mon, Apr 16, 2018 at 11:17 PM, Michele Marcucci <notifications@github.com

**Comment by jwb6658** [comment]
I second this. The .9 image produces a colored screen but does not actually load the OS.

**Comment by michelem09** [comment]
If you see here https://getminera.com/ there are more than 3 thousands Minera 0.9.0 running, so your problem must be with some specific configuration/hardware/dontknow you have.

Impossible for me to understand it without more informations.

**Comment by jwb6658** [comment]
The number running has no correlation to the problem at hand.

https://www.adafruit.com/product/3775?gclid=EAIaIQobChMIrZ2UhN342gIVyIqzCh3y9QrxEAQYASABEgLEivD_BwE

It’s the newest version of the Pi. OOB configuration. No changes. I just installed raspian and installed it manually because the image isn’t compatible.

**Comment by michelem09** [comment]
I will buy a Rpi 3 B+

**Comment by CryptoBlockchainTechnologies** [comment]
I can confirm with a 3B+ that I had the same block color image when I boot up. I figured out the issue is with the start.elf files.

1. Write the image file as directed
2. After the image is written open the drive listed as boot
3. Rename the old start.elf files to start_old.elf etc...
4. Copy either the start.elf files I have attached here or from a most recent Raspian image.
Should work fine now. Someone let me know if this works for them also. I spent all day on figuring this one out.





[start_files.zip](https://github.com/getminera/minera/files/2316652/start_files.zip)

**Comment by neiluj46** [comment]
Hello,

the file works perfectly,

however, I have a problem,

my rspberry has no IP address or is not detected by my internet box,

an idea?

**Comment by CryptoBlockchainTechnologies** [comment]
try ifconfig. should tell you the IP address. Normally 192.161.1.xxx

**Comment by CryptoBlockchainTechnologies** [comment]
typo should be 192.168.1.xxx

**Comment by neiluj46** [comment]
Ok it works

Now i want to enable my wifi on rspb pi3 b +
  
iwconfig :  eth0 and lo : no wirless extention 

Can I activate my wifi?

**Comment by michelem09** [comment]
v0.9.1 should work out-of-box with RPI B+

For wifi check `sudo wicd-curses`
