### ISSUE TITLE
Unresponsive with many Antminers

### ISSUE THREAD

**Issue by vancrypto** [getminera/minera#229]
The Dashboard is unresponsive with hundreds of Antminer S9's while running on a Raspberry Pi 3 Model B.

**Comment by michelem09** [comment]
Yep, I know, unfortunately Minera is not able to handle hundreds of machines.

**Comment by gnanet** [comment]
I wanted to wait for @michelem09  response, because i remember, he already mentioned this somewhere.

I was thinking a lot about the topic already, and a logical solution would be to have some background daemon, that continously polls the huge amount of networked miners, and a frontend could use the timestamp of the responses to see non-responding miners, and to create the statistical information the mining-operator wants to see,

**Comment by michelem09** [comment]
Sure it's possible and probably the right way to go, the problem is the lack of time to put my hands on Minera.

**Comment by gnanet** [comment]
It is still hypothesis, i only wanted to note, that managing 50-100 + networked miners is not an easy task. Additionally to the lack of time, my missing/insufficient knowledge of programming is also a show stopper.
